### ISSUE TITLE
Feature Request: flexible "custom" card

### ISSUE THREAD

**Issue by larsiusprime** [nospoone/monologue#11]
A single kind of "custom" card could cover a lot of use cases and simplify workflows.

Here's what I'm using now:
![already](https://cloud.githubusercontent.com/assets/739064/14123001/d8d0563c-f5c3-11e5-97b9-b53657937fbf.png)

This works, but I have to put all of my fields in one big text field, and then process them out later with parsing. I also have to attach a separate branch node, which isn't too much of a big deal, but I can only check it against variables, so I have to rig that up custom: by making a popup appear after a text node, note the user's selection ('yes' or 'no') and then feed that back into the Monologue Controller as the special "yesOrNo" variable, then run the tree forward.

Something like this maybe?

![custom](https://cloud.githubusercontent.com/assets/739064/14123113/9c1357ac-f5c4-11e5-80fc-ffeb784a5a2f.png)

This would let the user build a custom card out of separate pieces. The pieces are:

- Key / Value pair. A name and a value. Even just two strings would be enough to get started, we could make it fancier with types/validation later.
- A simple brancher (only one allowed per node): for feeding back the user's information from the host. On the editor side, there's one brancher per node, and it can be of different types. Bool implies exactly two exit nodes (true & false), any other type would allow the user to specify multiple exit nodes. For ultra fanciness a special customizable condition could be chosen for each exit condition but I think it's probably best just to start with a simple enumeration, and begin with only bool true/false. It would be nice to be able to put insta-firetongue'd labels on the exit nodes too, so we could use them in the host to label popup buttons, etc.

**Comment by larsiusprime** [comment]
Here's some more feedback on this. 

Here's a real-world project file:
https://gist.github.com/larsiusprime/bbaabc0ac4341e42484b0667c3332e70

Screenshot:
![monologueexample](https://cloud.githubusercontent.com/assets/739064/14531054/60fcb83e-0221-11e6-863c-2bf3ebbc33b5.png)

Detail:
![monologueexample_detail](https://cloud.githubusercontent.com/assets/739064/14531080/788af484-0221-11e6-9b4a-d2aadd2c3c4a.png)

I've written my own parser in my Host to handle this workflow I've kind of settled into. What I'll do is create a bunch of key-value pairs in the field itself, and then interpret those according to whatever the proper current context is. This lets me jam extra functionality into the "text" node, and gives me an idea for what a really versatile custom node might look like. 

I use "voices" to basically denote the "type" of node that this is in my host, and I generate a specific custom popup to match that. It looks for certain special fields (title:something, body:something), and interprets the rest according to the specific popup. In the case of the "radios" voice, every key value pair that isn't "special" gets treated as a radio value.

![monologuepopupradio](https://cloud.githubusercontent.com/assets/739064/14531215/03c422be-0222-11e6-904c-85309b515caa.png)

I do the same thing with checkboxes:

![monologuepopupcheckbox](https://cloud.githubusercontent.com/assets/739064/14531276/3cc67328-0222-11e6-83e6-ca2780901bce.png)

So a lot can be done just by having the ability to add arbitrary key:value pairs to a node. Honestly there's no reason I had to repurpose the "voice" dropdown, I could have just added a "type:checkboxes" or whatever, but I figured I'd use it because it was there.

So I think you see how a flexible custom node could be created that could serve most purposes without being too narrow:

-- Allow user to add arbitrary key:value pairs, giving the field a name and a value
-- Allow user to add an arbitrary number of exit nodes that are also key:value pairs

Inevitably we'll have more complex use cases that might call for entirely new specific node types, but I think this kind of generic thing will have a lot of power. It's nice because you don't have to generate a whole new node "class" just to add a new field to something, you just pop it in there. Right now I'm doing this just by adding new lines, but it would be nice to have them as proper fields because it'd be harder to make a mistake and easier to see what's going on.

**Comment by nospoone** [comment]
This is now all possible with the new fancy node editor :+1:
