### ISSUE TITLE
Feature request: "switch" card

### ISSUE THREAD

**Issue by larsiusprime** [nospoone/monologue#14]
The branch node gets the job done, but nested ifs can get kind of messy:

![switchnode](https://cloud.githubusercontent.com/assets/739064/14466941/7b747faa-009e-11e6-9ebd-e551e47d195e.png)

Would be nice to have a "switch" node that can stack various choices more easily. I imagine it would have a button at the bottom to add conditions, and it would require you to have a "default" condition as well.

**Comment by nospoone** [comment]
I've been wanting to do this as well, I'll try to get it in _soonish_.

**Comment by nospoone** [comment]
This is now possible, all branch nodes can now have "unlimited" conditions.
