### ISSUE TITLE
Export TSV's with <N> instead of \n

### ISSUE THREAD

**Issue by larsiusprime** [nospoone/monologue#15]
Right now the exported TSV files from monologue seem to be created with "\n" tokens on the JS side,  which results in real endlines in the files. Unfortunately the TSV file format *uses* real endlines to separate lines, so any monologue text blob with a real line break in it will not be properly parsed by Firetongue.

There's two big rules that have be adhered to for TSV files:
- No real endlines used except as a separator between lines
- No real tabs used except as a separator between cells

There's two solutions:
- Use the special firetongue token `<N>` wherever an endline is detected prior to exporting the TSV
- Use the CSV format instead and properly quote all fields

I recommend the first. What do you think?

**Comment by nospoone** [comment]
I can easily do the first option, I'm pretty sure.

**Comment by larsiusprime** [comment]
One more thing -- now when you load info back you need to change the <N>'s back to real endlines for display in Monologue tool :)
